require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - node_modules/**/*
    - bin/**/*
    - Gemfile

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false