require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - node_modules/**/*
    - bin/**/*
    - Gemfile

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Enabled: false

Style/Documentation:
  # TODO: Enable
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false