require: rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - node_modules/**/*
    - bin/**/*
    - Gemfile

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantReturn:
  Enabled: false