default: &default
  adapter:  postgresql
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000
  encoding: unicode
  username: gpuser
  password: vatruchuji
  host:     localhost
  template: template0

development:
  <<: *default
  database: gpapi_dev

test:
  <<: *default
  database: gpapi_test

production:
  <<: *default
  database: gpapi
